Spring Boot web task.
TkachukTara/Book-Store pull request #2
Opened 2024-01-31 13:15 UTC by TkachukTara

2024-02-01 09:25 UTC, Rommelua commented on src/main/java/book/store/dto/CreateBookRequestDto.java
> +    private Long id;
```suggestion
```

2024-02-01 09:25 UTC, Rommelua commented on src/main/java/book/store/service/impl/BookServiceImpl.java
> +        book.setIsbn("Isbn" + new Random().nextInt(1000));
we should have it in CreateBookRequestDto 
```suggestion
```

2024-02-01 21:14 UTC, MentorMA requested changes

2024-02-01 21:14 UTC, MentorMA commented on src/main/java/book/store/controller/BookController.java
> +
Why do you need an empty line at start of class

2024-02-01 21:14 UTC, MentorMA commented on src/main/java/book/store/dto/CreateBookRequestDto.java
> +    private String isbn = "Isbn" + new Random().nextInt(1000);
```suggestion
    private String isbn;
```

2024-02-01 21:14 UTC, MentorMA commented on src/main/java/book/store/dto/CreateBookRequestDto.java
> +    private String isbn = "Isbn" + new Random().nextInt(1000);
Why do you init it here?

2024-02-02 10:54 UTC, koval-kn approved these changes

2024-02-02 11:37 UTC, merged