Spring Boot Data JPA task!V1
TkachukTara/Book-Store pull request #3
Opened 2024-02-05 15:16 UTC by TkachukTara

2024-02-05 15:58 UTC, okuzan requested changes
Change spring.jpa.hibernate.ddl-auto property value to validate
PUT: /api/books/{id} (Update a specific book)

2024-02-05 15:58 UTC, okuzan commented on pom.xml
> +
```suggestion
```

2024-02-05 15:58 UTC, okuzan commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/create-books-table.yaml
```suggestion
      file: db/changelog/changes/create-books-table.yaml
      
```

2024-02-05 15:58 UTC, okuzan commented on src/main/resources/db/changelog/changes/create-books-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false
                    
```

2024-02-05 15:58 UTC, okuzan commented on src/main/java/book/store/model/Book.java
> +@Where(clause = "is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE books SET is_deleted = TRUE WHERE id = ?")
@Where(clause = "is_deleted = FALSE")
```

2024-02-06 10:56 UTC, Rommelua commented on src/main/java/book/store/dto/UpdateBookRequestDto.java
> +    }
delete this constructor

2024-02-06 10:56 UTC, Rommelua commented on src/main/java/book/store/service/impl/BookServiceImpl.java
> +        bookFromDb.setId(id);
check if id exist in DB

2024-02-07 09:56 UTC, Rommelua requested changes

2024-02-07 09:56 UTC, Rommelua commented on src/main/java/book/store/service/impl/BookServiceImpl.java
> +        Book bookFromDb = bookMapper.toModel(updatedBook);
Why bookFrom**Db** ?

2024-02-07 09:56 UTC, Rommelua commented on src/main/java/book/store/service/impl/BookServiceImpl.java
> +        bookFromDb.setId(id);
not fixed

2024-02-08 08:26 UTC, merged